// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var ordble, window_size;
    window_size = $(window).width();
    $("article.course").css({
      "height": (window_size / 16) * 9
    });
    ordble = $("#ordble > .order_description");
    return $(window).scroll(function() {
      var sc;
      sc = $(this).scrollTop();
      console.log(sc);
      if (sc > 110) {
        ordble.css({
          "position": "fixed",
          "top": 40
        });
      } else {
        ordble.css({
          "position": "absolute",
          "top": 80
        });
      }
      if (sc > 580) {
        return ordble.fadeOut();
      } else {
        return ordble.fadeIn();
      }
    });
  });

}).call(this);
